version: '2'

services:
 thredds:
    image: unidata/thredds-docker:4.6.10
    ports:
      - '80:8080'
    container_name: thredds
    volumes:
      - ./catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - ./target/s3datasetsource-1.0-SNAPSHOT-jar-with-dependencies.jar:/usr/local/tomcat/webapps/thredds/WEB-INF/lib/s3datasetsource-1.0-SNAPSHOT-jar-with-dependencies.jar