version: '2'

services:
 thredds:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '80:8080'
    container_name: thredds
    volumes:
      - ./threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - ./target/s3datasetsource-1.0-SNAPSHOT-jar-with-dependencies.jar:/usr/local/tomcat/webapps/thredds/WEB-INF/lib/s3datasetsource-1.0-SNAPSHOT-jar-with-dependencies.jar